-- Clear demo dataset generated by large_demo_seed_v2.sql.
-- Safe to rerun: removes only rows marked with seed signature/prefix.

do $$
declare
  v_seed_signature constant text := 'ops-v2-20260416-a1';
  v_seed_prefix constant text := '[SEED-V2]';
begin
  delete from public.ticket_comments
  where content like v_seed_prefix || '%';

  delete from public.outbound_messages
  where coalesce(subject, '') like v_seed_prefix || '%'
     or coalesce(content, '') like v_seed_prefix || '%';

  delete from public.notifications
  where coalesce(data ->> 'seed_signature', '') = v_seed_signature;

  delete from public.audit_logs
  where coalesce(metadata ->> 'seed_signature', '') = v_seed_signature;

  delete from public.customer_tags
  where exists (
    select 1
    from public.customers c
    where c.id = customer_tags.customer_id
      and (
        coalesce(c.custom_fields ->> 'seed_signature', '') = v_seed_signature
        or lower(coalesce(c.email, '')) like '%@demo-seed-v2.nexcrm.local'
      )
  );

  delete from public.customer_notes
  where exists (
    select 1
    from public.customers c
    where c.id = customer_notes.customer_id
      and (
        coalesce(c.custom_fields ->> 'seed_signature', '') = v_seed_signature
        or lower(coalesce(c.email, '')) like '%@demo-seed-v2.nexcrm.local'
      )
  );

  delete from public.tasks
  where title like v_seed_prefix || '%';

  delete from public.deals
  where title like v_seed_prefix || '%';

  delete from public.support_tickets
  where title like v_seed_prefix || '%';

  delete from public.transactions
  where invoice_code like 'SEED-%'
     or coalesce(notes, '') like v_seed_prefix || '%';

  delete from public.campaign_recipients
  where exists (
    select 1
    from public.campaigns c
    where c.id = campaign_recipients.campaign_id
      and c.name like v_seed_prefix || '%'
  );

  delete from public.campaigns
  where name like v_seed_prefix || '%';

  delete from public.automation_rules
  where name like v_seed_prefix || '%';

  delete from public.tags
  where name like v_seed_prefix || '%';

  delete from public.customers
  where coalesce(custom_fields ->> 'seed_signature', '') = v_seed_signature
     or lower(coalesce(email, '')) like '%@demo-seed-v2.nexcrm.local';
end $$;
