/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans, "DM Sans")', "sans-serif"],
        display: ['var(--font-sans, "DM Sans")', "sans-serif"],
        mono: ['var(--font-mono, "JetBrains Mono")', "ui-monospace", "monospace"],
      },
      fontSize: {
        "2xs": ["var(--text-2xs, 0.625rem)", { lineHeight: "1rem" }],
        xs: ["var(--text-xs, 0.6875rem)", { lineHeight: "1rem" }],
        sm: ["var(--text-sm, 0.8125rem)", { lineHeight: "1.125rem" }],
        base: ["var(--text-base, 0.9375rem)", { lineHeight: "1.375rem" }],
        lg: ["var(--text-lg, 1.0625rem)", { lineHeight: "1.5rem" }],
        xl: ["var(--text-xl, 1.25rem)", { lineHeight: "1.75rem" }],
        "2xl": ["var(--text-2xl, 1.5rem)", { lineHeight: "2rem" }],
        "3xl": ["var(--text-3xl, 2rem)", { lineHeight: "2.25rem" }],
        "4xl": ["var(--text-4xl, 2.5rem)", { lineHeight: "2.75rem" }],
      },
      spacing: {
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        "page-desktop": "var(--page-padding-desktop, 1.5rem)",
        "page-tablet": "var(--page-padding-tablet, 1rem)",
        "card-inner": "var(--card-padding, 1.25rem)",
        "field-gap": "var(--form-field-gap, 1rem)",
        "modal-inner": "var(--modal-padding, 1.5rem)",
      },
      colors: {
        border: "rgb(var(--border-soft-rgb, 226 230 237) / <alpha-value>)",
        input: "rgb(var(--bg-inset-rgb, 232 235 240) / <alpha-value>)",
        ring: "rgb(var(--accent-rgb, 37 99 235) / <alpha-value>)",
        background: "rgb(var(--bg-canvas-rgb, 248 249 251) / <alpha-value>)",
        foreground: "rgb(var(--text-primary-rgb, 15 21 35) / <alpha-value>)",
        primary: {
          DEFAULT: "rgb(var(--accent-rgb, 37 99 235) / <alpha-value>)",
          foreground: "rgb(var(--accent-foreground-rgb, 255 255 255) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "rgb(var(--bg-subtle-rgb, 241 243 247) / <alpha-value>)",
          foreground: "rgb(var(--text-secondary-rgb, 75 85 104) / <alpha-value>)",
        },
        card: {
          DEFAULT: "rgb(var(--bg-surface-rgb, 255 255 255) / <alpha-value>)",
          foreground: "rgb(var(--text-primary-rgb, 15 21 35) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "rgb(var(--bg-overlay-rgb, 255 255 255) / <alpha-value>)",
          foreground: "rgb(var(--text-primary-rgb, 15 21 35) / <alpha-value>)",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--accent-light-rgb, 239 246 255) / <alpha-value>)",
          foreground: "rgb(var(--accent-rgb, 37 99 235) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "rgb(var(--danger-rgb, 220 38 38) / <alpha-value>)",
          foreground: "rgb(var(--accent-foreground-rgb, 255 255 255) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--success-rgb, 5 150 105) / <alpha-value>)",
          soft: "hsl(var(--success-soft) / <alpha-value>)",
          bg: "rgb(var(--success-bg-rgb, 240 253 244) / <alpha-value>)",
          border: "rgb(var(--success-border-rgb, 187 247 208) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--warning-rgb, 217 119 6) / <alpha-value>)",
          soft: "hsl(var(--warning-soft) / <alpha-value>)",
          bg: "rgb(var(--warning-bg-rgb, 255 251 235) / <alpha-value>)",
          border: "rgb(var(--warning-border-rgb, 253 230 138) / <alpha-value>)",
        },
        info: {
          DEFAULT: "rgb(var(--info-rgb, 8 145 178) / <alpha-value>)",
          soft: "hsl(var(--info-soft) / <alpha-value>)",
          bg: "rgb(var(--info-bg-rgb, 240 249 255) / <alpha-value>)",
          border: "rgb(var(--info-border-rgb, 186 230 253) / <alpha-value>)",
        },
      },
      boxShadow: {
        xs: "var(--shadow-xs, 0 1px 2px rgba(0, 0, 0, 0.05))",
        sm: "var(--shadow-sm, 0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06))",
        md: "var(--shadow-md, 0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.05))",
        lg: "var(--shadow-lg, 0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05))",
        xl: "var(--shadow-xl, 0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04))",
        soft: "var(--shadow-md, 0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.05))",
        panel: "var(--shadow-xl, 0 20px 25px rgba(0, 0, 0, 0.1), 0 10px 10px rgba(0, 0, 0, 0.04))",
        focus: "var(--shadow-focus, 0 0 0 3px rgba(37, 99, 235, 0.08))",
      },
      borderRadius: {
        xs: "var(--radius-xs, 3px)",
        sm: "var(--radius-sm, 6px)",
        md: "var(--radius-md, 10px)",
        lg: "var(--radius-lg, 14px)",
        xl: "var(--radius-xl, 18px)",
        "2xl": "var(--radius-xl, 18px)",
        full: "var(--radius-full, 9999px)",
      },
      transitionTimingFunction: {
        modal: "cubic-bezier(0.32, 0.72, 0, 1)",
      },
      transitionDuration: {
        150: "150ms",
        200: "200ms",
        250: "250ms",
      },
    },
  },
  plugins: [],
}
